#pragma once

#include "state.h"
#include "stateMachine.h"

class NPC
{
private:

	stateMachine<NPC>* NPCSM; //Each NPC has its own State Machine
	float DIR; //direction angle from 0-359

public:
	 NPC(); //Constructor
	~NPC(); //Deconstructor

	/** @update
	* @brief: The update function for the AI
	* @desciption: Must be called constantly for effective use of the State Machine
	*/
	void update(); //Update - must be called on each glutDisplayFunc or whenever is updated

	/** @SetDir
	* @brief: Allows the State Machine access to the NPC's direction value, allowing for it to be randomised
	* @description: This funciton is called by the State Machine for each individual AI, and is needed for successful funcionality
	* @param: a single int, that represents the randomised number, generated by the state, in NPCStates.CPP
	*/
	void SetDir(float RandVal); //THIS MUST BE ADDED for the AI to be able to change its DIR

	/** @GetDir
	* @brief: Allows for public access to the NPC's DIR value
	* @notes: not particularly needed, just nice to have, 
	*/
	float GetDir();
};

